variables:
  HEROKU_API_KEY: $HEROKU_TOKEN
  APP_NAME: "milwaukee-internationals-core"

stages:
  - build

docker-build:
  stage: deploy
  image: docker
  resource_group: heroku
  only:
    - master
  allow_failure: false
  script:
    - apk add bash curl nodejs
    - heroku container:login
    - heroku container:push --app $APP_NAME web
    - heroku container:release web