include:
  - local: ".gitlab-ci/.gitlab-ci-db-backup.yml"
  - local: ".gitlab-ci/.gitlab-ci-deploy.yml"

stages:
  - deploy
  - backup

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - if: "$WHATEVER"
      when: never
  script:
    - echo "Running build"

backup:
  stage: backup
  rules:
    - if: "$WHATEVER"
  script:
    - echo "Running backup"
