image: docker:latest
services:
  - docker:sue445/heroku-cli

variables:
  HEROKU_API_KEY: $HEROKU_TOKEN
  APP_NAME: "milwaukee-internationals-core"

stages:
  - build

docker-build:
  stage: build
  only:
    - master
  allow_failure: false
  script:
    - heroku container:login
    - heroku container:push --app $APP_NAME web
    - heroku container:release web