image: docker:latest
services:
  - name: docker:dind
    alias: docker

variables:
  HEROKU_API_KEY: $HEROKU_TOKEN
  APP_NAME: "milwaukee-internationals-core"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"

stages:
  - deploy

docker-build:
  stage: deploy
  resource_group: heroku
  only:
    - master
  allow_failure: false
  script:
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku container:push --app $APP_NAME web
    - heroku container:release web