include:
  - local: "ci/backup.gitlab-ci.yml"
    rules:
      - if: $CI_COMMIT_BRANCH == "master" && $WHATEVER
  # - local: "ci/deploy.gitlab-ci.yml"
  #   rules:
  #     - if: $CI_COMMIT_BRANCH == "master" && $WHATEVER == null