variables:
  HEROKU_API_KEY: $HEROKU_TOKEN
  APP_NAME: "milwaukee-internationals-core"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"
  HEROKU_USERNAME: "hesamian@uwm.edu"

services:
  - docker:dind

stages:
  - deploy

docker-build:
  stage: deploy
  image: docker:dind
  resource_group: heroku
  only:
    - master
  allow_failure: false
  script:
    - docker version
    - apk add --no-cache bash curl nodejs make gcompat build-base m4 ncurses
    - apk add --no-cache --virtual=build-dependencies wget ca-certificates
    - curl https://cli-assets.heroku.com/install.sh | sh
    - echo $HEROKU_API_KEY | docker login --username=$HEROKU_USERNAME --password-stdin registry.heroku.com
    - heroku container:push --app $APP_NAME web
    - heroku container:release web