include:
  - local: '.gitlab-ci/.gitlab-ci-db-backup.yml'
  - local: '.gitlab-ci/.gitlab-ci-deploy.yml'

stages:
  - deploy
  - backup

deploy:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - if: '$WHATEVER'
      when: never

build:
  stage: deploy
  rules:
    - if: '$WHATEVER'