image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  HEROKU_TOKEN: $HEROKU_TOKEN
  APP_NAME: "milwaukee-internationals-core"

stages:
  - build

docker-build:
  stage: build
  only:
    - master
  allow_failure: false
  script:
    - docker build -f Dockerfile --iidfile imageid.txt -t registry.heroku.com/$APP_NAME/web .
    - docker login -u _ -p $HEROKU_TOKEN registry.heroku.com
    - docker push registry.heroku.com/$APP_NAME/web
    - apk add --no-cache curl
    - echo "Docker Image ID is $(cat imageid.txt)"
    - |-
      curl -X PATCH https://api.heroku.com/apps/$APP_NAME/formation --header "Content-Type: application/json" --header "Accept: application/vnd.heroku+json; version=3.docker-releases" --header "Authorization: Bearer ${HEROKU_TOKEN}" --data '{ "updates": [ { "type": "web", "docker_image": "$(docker inspect registry.heroku.com/$APP_NAME/web --format={{.Id}})" } ] }'
