include:
  - local: "ci/backup.gitlab-ci.yml"
    rules:
      - if: $CI_COMMIT_BRANCH == "master" && $SCHEDULED_BACKUP
  - local: "ci/deploy.gitlab-ci.yml"
    rules:
      - if: $CI_COMMIT_BRANCH == "master" && $SCHEDULED_BACKUP == null
