name: Backup and Upload

on:
  schedule:
    - cron: '43 22 * * *'
  push:
    branches:
      - master

env:
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_NAME: milwaukee-internationals-backup

jobs:
  capture-backup:
    name: Capture DigitalOcean Backup
    runs-on: ubuntu-latest
    container:
      image: postgres:17-alpine
    steps:
      - name: Dump DigitalOcean PostgreSQL Database
        env:
          DATABASE_URL: ${{ secrets.MKE_INTERNATIONAL_DATABASE_URL }}
        run: |
          pg_dump "$DATABASE_URL" -F c -f db.dump

      - name: Upload Backup as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: db-dump
          path: db.dump

  upload-backup:
    name: Upload Backup to S3
    runs-on: ubuntu-latest
    needs: capture-backup
    steps:
      - name: Download Backup Artifact
        uses: actions/download-artifact@v4
        with:
          name: db-dump
          path: .

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_DEFAULT_REGION

      - name: Upload to S3
        run: |
          export CI_JOB_TIMESTAMP=$(date --utc "+%Y-%m-%dT%H:%M:%S")
          export S3_OBJECT_NAME="$CI_JOB_TIMESTAMP.dump"
          aws s3 cp db.dump s3://$BUCKET_NAME/$S3_OBJECT_NAME
