name: Backup and Upload

on:
  push:
    branches:
      - master

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
  APP_NAME: "milwaukee-internationals-core"
  HEROKU_EMAIL: "hesamian@uwm.edu"
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_NAME: milwaukee-internationals-backup

jobs:
  capture-backup:
    name: Capture Heroku Backup
    runs-on: ubuntu-latest
    steps:
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl nodejs npm
          npm install -g heroku
      - name: Login to Heroku
        run: heroku auth:token
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
      - name: Capture Heroku Backup
        run: heroku pg:backups:capture --app $APP_NAME
      - name: Download Backup
        run: heroku pg:backups:url --app $APP_NAME | xargs -I{} curl -o db.dump "{}"
      - name: Upload Backup as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: db-dump
          path: db.dump

  upload-backup:
    name: Upload Backup to S3
    runs-on: ubuntu-latest
    needs: capture-backup
    steps:
      - name: Download Backup Artifact
        uses: actions/download-artifact@v3
        with:
          name: db-dump
          path: .
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_DEFAULT_REGION
      - name: Upload to S3
        run: |
          export CI_JOB_TIMESTAMP=$(date --utc "+%Y-%m-%dT%H:%M:%S")
          export S3_OBJECT_NAME="$CI_JOB_TIMESTAMP.dump"
          aws s3 cp db.dump s3://$BUCKET_NAME/$S3_OBJECT_NAME
